name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install modules
        run: pnpm install && pnpm build
      - name: Run ESLint
        run: pnpm lint
      - name: Run Jest tests
        run: pnpm test
